name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_as:
        description: 'Override version (e.g., 0.3.3)'
        required: false
        default: ''

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4
        with:
          config-file: .release-please-config.json
          release-as: ${{ inputs.release_as }}
          token: ${{ secrets.RELEASE_PLEASE_TOKEN != '' && secrets.RELEASE_PLEASE_TOKEN || github.token }}
