name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 20.x
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - run: npm pack --dry-run
      - name: Publish to npm (OIDC preferred, token fallback)
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -e
          if [ -n "${NPM_TOKEN}" ]; then
            echo "Using NPM_TOKEN secret"
            npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
            npm publish --access public
          else
            echo "Using GitHub OIDC (Trusted Publishing)"
            npm publish --provenance --access public
          fi
