name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20.x
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - run: npm pack --dry-run
      - name: Publish to npm (OIDC preferred, token fallback)
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -e
          if [ -n "${NPM_TOKEN}" ]; then
            echo "Using NPM_TOKEN secret"
            npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
            npm publish --access public
          else
            echo "Using GitHub OIDC (Trusted Publishing)"
            npm publish --provenance --access public
          fi
