name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_as:
        description: 'Override version (e.g., 0.3.3)'
        required: false
        default: ''

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.json
          release-as: ${{ inputs.release_as }}
          token: ${{ secrets.RELEASE_PLEASE_TOKEN != '' && secrets.RELEASE_PLEASE_TOKEN || github.token }}
