name: Release Please

on:
  workflow_dispatch:
    inputs:
      release_as:
        description: 'Override version (e.g., 0.3.3)'
        required: false
        default: ''

jobs:
  noop-guard:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped: manual-only workflow"

  release-please:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.json
          release-as: ${{ inputs.release_as }}
          token: ${{ secrets.RELEASE_PLEASE_TOKEN != '' && secrets.RELEASE_PLEASE_TOKEN || github.token }}
