name: Update Branch Protection (manual)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to protect'
        required: true
        default: 'main'

jobs:
  noop-guard:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped: manual-only workflow"

  protect:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Update branch protection via REST API
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ inputs.branch }}
        run: |
          set -euo pipefail
          if [ -z "${GH_TOKEN:-}" ]; then
            echo "GH_ADMIN_TOKEN secret is required (repo admin:branch permissions)." >&2
            exit 1
          fi
          owner=$(echo "$REPO" | cut -d/ -f1)
          repo=$(echo "$REPO" | cut -d/ -f2)
          url="https://api.github.com/repos/$owner/$repo/branches/$BRANCH/protection"
          # Required checks must match CI job names exactly
          payload=$(cat <<'JSON'
          {
            "required_status_checks": {
              "strict": true,
              "contexts": [
                "CI / build-and-test (18.x) (pull_request)",
                "CI / build-and-test (20.x) (pull_request)",
                "Commitlint / commitlint (pull_request)"
              ]
            },
            "enforce_admins": false,
            "required_pull_request_reviews": {
              "required_approving_review_count": 1
            },
            "restrictions": null,
            "allow_force_pushes": false,
            "allow_deletions": false
          }
JSON
          )
          curl -fsSL -X PUT "$url" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "$payload"
          echo "Updated protection on $BRANCH with required checks."
